# Generated by Django 2.0.6 on 2020-04-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationKeys',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
